### ISSUE TITLE
Promise issue

### ISSUE THREAD

**Issue by potatoqualitee** [sketchbuch/vsc-workspace-sidebar#29]
Hello! Thank you so much for this extension. I'm using it to learn TypeScript. I changed it to webpack which runs advanced tests (I think) and am running into this problem.

`Promise<WsFiles | false>' is not assignable to parameter of type 'AsyncThunkPayloadCreator<false, void, {}>'.`

```
ERROR in C:\github\vscode-filename-search\src\webviews\Workspace\store\fetch.ts
./src/webviews/Workspace/store/fetch.ts 7:47-65
[tsl] ERROR in C:\github\vscode-filename-search\src\webviews\Workspace\store\fetch.ts(7,48)
      TS2345: Argument of type '() => Promise<WsFiles | false>' is not assignable to parameter of type 'AsyncThunkPayloadCreator<false, void, {}>'.
  Type 'Promise<false | WsFiles>' is not assignable to type 'AsyncThunkPayloadCreatorReturnValue<false, {}>'.
    Type 'Promise<false | WsFiles>' is not assignable to type 'Promise<false | RejectWithValue<unknown, unknown>>'.
      Type 'false | WsFiles' is not assignable to type 'false | RejectWithValue<unknown, unknown>'.
        Type 'WsFiles' is not assignable to type 'false | RejectWithValue<unknown, unknown>'.
          Type 'string[]' is missing the following properties from type 'RejectWithValue<unknown, unknown>': payload, meta, _type
ts-loader-default_e3b0c44298fc1c14
 @ ./src/webviews/Workspace/WorkspaceViewProvider.ts 33:16-40
 @ ./src/webviews/index.ts 14:13-57
 @ ./src/core/activate.ts 6:19-41
 @ ./src/extension.ts 4:17-43
```

I believe I saw earlier when compiling your version, that this error is tolerated in current versions of vs code but won't be in the future. Do you have any fix suggestions? Promises are currently way beyond me.

**Comment by potatoqualitee** [comment]
Fixed it! Unsure if my solution is right but after reading this issue, https://github.com/reduxjs/redux-toolkit/issues/587

I changed `src\webviews\Workspace\WorkspaceViewProvider.interface.ts` to use `export type WsFiles = any;`

Then in `src\utils\fs\getFilenamesOfType.ts`, I changed it to this:

`return filenames.reduce((allFiles: any, curFile: string) => {`

Then it compiled 🥳

**Comment by sketchbuch** [comment]
Hi, you should not used any, there is a setting to disable use of any in tsconfig. Using any is basically like not using typescript! 

What exactly are you trying to do? What issue are you trying to fix?

**Comment by potatoqualitee** [comment]
ah ha! Found it. The broken promise warning shows up when you install the vsix from command line

```
> vsce package
> code --install-extension vsc-workspace-sidebar-1.2.8.vsix
Installing extensions...
(node:17000) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
Extension 'vsc-workspace-sidebar-1.2.8.vsix' was successfully installed.
(node:17000) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at Object.O [as canceled] (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1157)
    at T.cancel (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:62864)
    at T.dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63004)
    at k.dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63266)
    at W (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at d.clear (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
    at dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
    at dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
    at dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:11:7229)
    at W (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3634
    at Object.dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3706)
    at Object.W [as dispose] (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3567)
    at C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41195
    at Map.forEach (<anonymous>)
    at Ne.dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41182)
    at W (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at d.clear (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
    at dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
    at a.dispose (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
    at Object.g [as main] (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:51594)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async k (C:\Users\ctrlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:12:13756)
(node:17000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
